name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('web/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: ./web

      - name: Lint code
        run: bun run lint
        working-directory: ./web

      - name: Type check
        run: bun run typecheck
        working-directory: ./web

      - name: Format code
        run: bun run format
        working-directory: ./web
        continue-on-error: true

      - name: Run Knip
        run: bun run knip
        working-directory: ./web
        continue-on-error: true

      - name: Build project
        run: bun run build
        working-directory: ./web